sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t thrilok28021996/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thrilok28021996/react-test npm test

after_success:
  - docker build -t thrilok28021996/multi-client ./client
  - docker build -t thrilok28021996/multi-nginx ./nginx
  - docker build -t thrilok28021996/multi-server ./server
  - docker build -t thrilok28021996/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push thrilok28021996/multi-client
  - docker push thrilok28021996/multi-nginx
  - docker push thrilok28021996/multi-server
  - docker push thrilok28021996/multi-worker


deploy:
  provider: elasticbeanstalk
  region: region
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elastic bucket name
  bucket_path: docker-multi
  on:
    branch:master
  access_key_id: $AWS_ACESS_KEY
  secret_access_key:
    secure: $ AWS_ACESS_KEY